# Generated by Django 5.0.3 on 2024-03-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
